# Generated by Django 5.1.2 on 2024-12-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
