# Generated by Django 5.1.2 on 2024-12-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrequest',
            name='is_late',
        ),
        migrations.RemoveField(
            model_name='lessonrequest',
            name='requested_date',
        ),
    ]
