# Generated by Django 5.1.2 on 2024-11-23 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_course_invoice_term_admin_lesson_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='ProgrammingLanguage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tutorials.expertise'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='expertise',
            field=models.ManyToManyField(related_name='qualified_tutors', to='tutorials.expertise'),
        ),
    ]
