# Generated by Django 5.1.2 on 2024-12-04 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_remove_lessonrequest_is_late_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='requested_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
