# Generated by Django 5.1.2 on 2024-12-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_lessonrequest_is_late'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrequest',
            name='is_late',
        ),
    ]
