# Generated by Django 5.1.2 on 2024-12-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_lesson_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancellationrequest',
            old_name='isLate',
            new_name='is_late',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('active', 'Active')], default='active', max_length=20),
        ),
    ]
