# Generated by Django 5.1.2 on 2024-11-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_expertise_course_programminglanguage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='tutorials.lesson'),
        ),
    ]
