# Generated by Django 5.1.2 on 2024-12-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_lessonrequest_is_late_lessonrequest_requested_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='status',
            field=models.CharField(choices=[('pendingx', 'Pending'), ('allocatedy', 'Allocated'), ('rejectedz', 'Rejected')], default='pending', max_length=20),
        ),
    ]
