# Generated by Django 5.1.2 on 2024-12-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_rename_islate_cancellationrequest_is_late_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='status',
        ),
    ]
