# Generated by Django 5.1.2 on 2024-11-23 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_student_enrolled_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='rollover',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrolled_courses',
        ),
        migrations.RemoveField(
            model_name='tutorsession',
            name='date',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
