# Generated by Django 5.1.2 on 2024-12-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_lessonrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
