# Generated by Django 5.1.2 on 2024-11-24 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_remove_lesson_invoice_remove_lesson_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrequest',
            name='requested_start_date',
        ),
    ]
