# Generated by Django 5.1.2 on 2024-12-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_remove_lesson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
