# Generated by Django 5.1.2 on 2024-11-24 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_remove_lessonrequest_requested_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_lesson', to='tutorials.lessonrequest'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_minutes',
            field=models.PositiveIntegerField(choices=[('1 Hour', 60), ('2 Hours', 120)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='session',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_booked', False)), on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tutorials.tutorsession'),
        ),
    ]
