# Generated by Django 5.1.2 on 2024-11-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_lesson_request_alter_course_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='tutorsession',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_minutes',
            field=models.PositiveIntegerField(choices=[(60, '1 Hour'), (120, '2 Hours')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_per_hour',
            field=models.DecimalField(choices=[(20.0, 'Beginner: £20/hour'), (40.0, 'Intermediate: £40/hour'), (60.0, 'Advanced: £60/hour')], decimal_places=2, max_digits=5),
        ),
    ]
