# Generated by Django 5.1.2 on 2024-11-24 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_remove_lesson_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_lesson', to='tutorials.lessonrequest'),
        ),
        migrations.AlterField(
            model_name='tutorsession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course_Sessions', to='tutorials.course'),
        ),
        migrations.AlterField(
            model_name='tutorsession',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Term_Sessions', to='tutorials.term'),
        ),
        migrations.AlterField(
            model_name='tutorsession',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tutor_Sessions', to='tutorials.tutor'),
        ),
    ]
