# Generated by Django 5.1.2 on 2024-11-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_alter_tutorsession_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='start_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], default=0),
        ),
        migrations.AlterField(
            model_name='tutorsession',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
