# Generated by Django 5.1.2 on 2024-11-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_tutorsession_start_day_alter_tutorsession_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
