# Generated by Django 5.1.2 on 2024-11-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_tutorsession_start_day_alter_tutorsession_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='frequency',
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(choices=[(60, '1 Hour'), (120, '2 Hours')], default=60),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Every Two Weeks')], default='weekly', max_length=20),
        ),
    ]
