# Generated by Django 5.1.2 on 2024-11-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_lessonrequest_is_late'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrequest',
            name='is_late',
        ),
    ]
