# Generated by Django 5.1.2 on 2024-11-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_remove_course_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
