# Generated by Django 5.1.2 on 2024-11-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0013_tutorsession_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='rollover',
            field=models.BooleanField(default=True),
        ),
    ]
