# Generated by Django 5.1.2 on 2024-11-29 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0014_remove_lessonrequest_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_requests', to='tutorials.term'),
        ),
    ]
