# Generated by Django 5.1.2 on 2024-11-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0014_lesson_rollover'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], default=0),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='duration_minutes',
            field=models.PositiveIntegerField(choices=[(60, '1 Hour'), (120, '2 Hours')], default=60),
        ),
    ]
