# Generated by Django 5.1.2 on 2024-11-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0015_lesson_end_date_lesson_start_date_lesson_start_day_and_more'),
        ('tutorials', '0015_lessonrequest_term'),
    ]

    operations = [
    ]
