# Generated by Django 5.1.2 on 2024-11-29 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0016_merge_20241129_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_requests', to='tutorials.term'),
        ),
    ]
