# Generated by Django 5.1.2 on 2024-12-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0017_alter_lessonrequest_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
