# Generated by Django 5.1.2 on 2024-12-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0019_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Lesson',
            new_name='lesson',
        ),
    ]
