# Generated by Django 5.1.2 on 2024-12-03 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0020_rename_lesson_invoice_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='requested_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
