# Generated by Django 5.1.2 on 2024-12-05 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0021_lessonrequest_requested_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='Invoice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Lesson', to='tutorials.invoice'),
        ),
    ]
