# Generated by Django 5.1.2 on 2024-12-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0023_alter_lesson_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='Invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Lesson', to='tutorials.invoice'),
        ),
    ]
