# Generated by Django 5.1.2 on 2024-12-06 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0024_alter_lesson_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='Invoice',
        ),
    ]
