# Generated by Django 5.1.2 on 2024-12-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0025_remove_lesson_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorsession',
            name='course',
        ),
    ]
