# Generated by Django 5.1.2 on 2024-12-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0026_remove_tutorsession_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
